// src/infrastructure/firebase/seedMovies.js
// Run this once to populate Firestore with sample movies
// Usage: import and call seedMovies() from App.js once, then remove.
import { collection, doc, setDoc } from 'firebase/firestore';
import { db } from './config';

const SAMPLE_MOVIES = [
  {
    id: 'movie-009',
    title: 'El Caballero Oscuro',
    year: '2008',
    genre: 'Acción / Drama / Crimen',
    director: 'Christopher Nolan',
    synopsis:
      'Batman se enfrenta al Joker, un criminal anárquico que busca sumir Gotham en el caos absoluto mientras pone a prueba los límites morales del héroe.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    duration: '152 min',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-010',
    title: 'Gladiator',
    year: '2000',
    genre: 'Acción / Drama / Histórico',
    director: 'Ridley Scott',
    synopsis:
      'Un general romano traicionado busca venganza convirtiéndose en gladiador mientras lucha por restaurar el honor de su familia y de Roma.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTY3NTYzOTYwOF5BMl5BanBnXkFtZTcwNjY2MzU2Mw@@._V1_SX300.jpg',
    duration: '155 min',
    cast: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-011',
    title: 'Titanic',
    year: '1997',
    genre: 'Drama / Romance',
    director: 'James Cameron',
    synopsis:
      'Una joven aristócrata y un artista humilde viven un intenso romance a bordo del Titanic antes de que el legendario transatlántico se hunda en el Atlántico.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMDdmODU0YzktYzY1OS00ZmU3LWFmN2QtYzZjZjRkYjVjNTg0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    duration: '195 min',
    cast: ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-012',
    title: 'Origen',
    year: '2010',
    genre: 'Ciencia Ficción / Thriller',
    director: 'Christopher Nolan',
    synopsis:
      'Un ladrón especializado en robar secretos a través de los sueños recibe la misión inversa: implantar una idea en la mente de un objetivo.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjY3OF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg',
    duration: '148 min',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-013',
    title: 'Parásitos',
    year: '2019',
    genre: 'Drama / Thriller',
    director: 'Bong Joon-ho',
    synopsis:
      'Una familia de clase baja se infiltra poco a poco en el hogar de una familia adinerada, desencadenando una serie de acontecimientos impredecibles.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BYWZjMjY0YTUtNjY4My00YzE2LWFhYmUtMjgxNjY0MjZjZDI4XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    duration: '132 min',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-014',
    title: 'Whiplash',
    year: '2014',
    genre: 'Drama / Música',
    director: 'Damien Chazelle',
    synopsis:
      'Un joven baterista de jazz es sometido a un intenso y abusivo entrenamiento por parte de un exigente profesor que busca la perfección absoluta.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjY3OF5BMl5BanBnXkFtZTgwNTU0NDYzMjE@._V1_SX300.jpg',
    duration: '107 min',
    cast: ['Miles Teller', 'J.K. Simmons'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-015',
    title: 'El Silencio de los Corderos',
    year: '1991',
    genre: 'Thriller / Crimen',
    director: 'Jonathan Demme',
    synopsis:
      'Una joven agente del FBI busca la ayuda del brillante y peligroso psiquiatra Hannibal Lecter para capturar a un asesino en serie.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNzZhOTQ0YzAtYzYzZC00OTkzLWE3ZTctZGMzZGUwNjBhNzQ3XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    duration: '118 min',
    cast: ['Jodie Foster', 'Anthony Hopkins'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-016',
    title: 'Ciudad de Dios',
    year: '2002',
    genre: 'Crimen / Drama',
    director: 'Fernando Meirelles',
    synopsis:
      'La historia del crecimiento del crimen organizado en las favelas de Río de Janeiro desde los años 60 hasta los 80.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjA3OTkzODQ2OF5BMl5BanBnXkFtZTcwODQ2NjEzMw@@._V1_SX300.jpg',
    duration: '130 min',
    cast: ['Alexandre Rodrigues', 'Leandro Firmino'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-017',
    title: 'La La Land',
    year: '2016',
    genre: 'Romance / Musical',
    director: 'Damien Chazelle',
    synopsis:
      'Una aspirante a actriz y un músico de jazz se enamoran mientras persiguen sus sueños en Los Ángeles.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjA3OTkzODQ2OF5BMl5BanBnXkFtZTgwNjQ3NzQ3OTE@._V1_SX300.jpg',
    duration: '128 min',
    cast: ['Ryan Gosling', 'Emma Stone'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-018',
    title: 'El Renacido',
    year: '2015',
    genre: 'Aventura / Drama',
    director: 'Alejandro G. Iñárritu',
    synopsis:
      'Un explorador del siglo XIX lucha por sobrevivir en la naturaleza salvaje después de ser abandonado tras el ataque de un oso.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjA3OTkzODQ2OF5BMl5BanBnXkFtZTgwNzY3NzU5NzE@._V1_SX300.jpg',
    duration: '156 min',
    cast: ['Leonardo DiCaprio', 'Tom Hardy'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-019',
    title: 'Joker',
    year: '2019',
    genre: 'Drama / Thriller',
    director: 'Todd Phillips',
    synopsis:
      'La historia del origen del icónico villano mientras desciende hacia la locura en una sociedad que lo ignora y maltrata.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjAyMjkzNzQzNV5BMl5BanBnXkFtZTgwMDk2MTk5NjM@._V1_SX300.jpg',
    duration: '122 min',
    cast: ['Joaquin Phoenix', 'Robert De Niro'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-020',
    title: 'Avengers: Endgame',
    year: '2019',
    genre: 'Acción / Ciencia Ficción',
    director: 'Anthony y Joe Russo',
    synopsis:
      'Los Vengadores supervivientes se reúnen para revertir el devastador chasquido de Thanos y restaurar el universo.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjMxNjY2MzY4MV5BMl5BanBnXkFtZTgwNzY4NTYzNzM@._V1_SX300.jpg',
    duration: '181 min',
    cast: ['Robert Downey Jr.', 'Chris Evans', 'Scarlett Johansson'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-021',
    title: 'Braveheart',
    year: '1995',
    genre: 'Drama / Histórico',
    director: 'Mel Gibson',
    synopsis: 'William Wallace lidera la rebelión escocesa contra la opresión inglesa.',
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUrwZ_HBGuaK2h2zINA1NXKES2Wp25flUamg&s',
    duration: '178 min',
    cast: ['Mel Gibson', 'Sophie Marceau'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-022',
    title: 'Seven',
    year: '1995',
    genre: 'Thriller / Crimen',
    director: 'David Fincher',
    synopsis: 'Dos detectives persiguen a un asesino que basa sus crímenes en los siete pecados capitales.',
    posterUrl: 'https://m.media-amazon.com/images/I/61OsWbR83TL._AC_UF894,1000_QL80_.jpg',
    duration: '127 min',
    cast: ['Brad Pitt', 'Morgan Freeman'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-023',
    title: 'Django Desencadenado',
    year: '2012',
    genre: 'Western / Drama',
    director: 'Quentin Tarantino',
    synopsis: 'Un esclavo liberado busca rescatar a su esposa con ayuda de un cazarrecompensas.',
    posterUrl: 'https://m.media-amazon.com/images/I/91+5R1A6WSL._AC_UF1000,1000_QL80_.jpg',
    duration: '165 min',
    cast: ['Jamie Foxx', 'Christoph Waltz'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-024',
    title: 'Mad Max: Fury Road',
    year: '2015',
    genre: 'Acción / Ciencia Ficción',
    director: 'George Miller',
    synopsis: 'En un mundo postapocalíptico, Max ayuda a una rebelde a escapar de un tirano.',
    posterUrl: 'https://m.media-amazon.com/images/I/81bzAseuPYL._AC_UF894,1000_QL80_.jpg',
    duration: '120 min',
    cast: ['Tom Hardy', 'Charlize Theron'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-025',
    title: 'Blade Runner 2049',
    year: '2017',
    genre: 'Ciencia Ficción / Drama',
    director: 'Denis Villeneuve',
    synopsis: 'Un blade runner descubre un secreto que amenaza la estabilidad de la sociedad.',
    posterUrl: 'https://m.media-amazon.com/images/I/81E+onwuDOL._AC_UF894,1000_QL80_.jpg',
    duration: '164 min',
    cast: ['Ryan Gosling', 'Harrison Ford'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-026',
    title: 'El Gran Hotel Budapest',
    year: '2014',
    genre: 'Comedia / Drama',
    director: 'Wes Anderson',
    synopsis: 'Las aventuras de un excéntrico conserje y su protegido en un famoso hotel europeo.',
    posterUrl: 'https://m.media-amazon.com/images/I/91tOvvGoEnL._AC_UF1000,1000_QL80_.jpg',
    duration: '99 min',
    cast: ['Ralph Fiennes', 'Tony Revolori'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-027',
    title: 'La Vida es Bella',
    year: '1997',
    genre: 'Drama / Comedia',
    director: 'Roberto Benigni',
    synopsis: 'Un padre usa su imaginación para proteger a su hijo en un campo de concentración.',
    posterUrl: 'https://m.media-amazon.com/images/I/51+zvkSGCUL._AC_UF894,1000_QL80_.jpg',
    duration: '116 min',
    cast: ['Roberto Benigni'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-028',
    title: 'El Pianista',
    year: '2002',
    genre: 'Drama / Histórico',
    director: 'Roman Polanski',
    synopsis: 'Un músico judío lucha por sobrevivir en la Varsovia ocupada por los nazis.',
    posterUrl: 'https://m.media-amazon.com/images/I/814+sZoDjXL._AC_UF894,1000_QL80_.jpg',
    duration: '150 min',
    cast: ['Adrien Brody'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-029',
    title: 'Shutter Island',
    year: '2010',
    genre: 'Thriller / Misterio',
    director: 'Martin Scorsese',
    synopsis: 'Un agente investiga la desaparición de una paciente en un hospital psiquiátrico.',
    posterUrl: 'https://m.media-amazon.com/images/I/91tsTRkHXgL._AC_UF894,1000_QL80_.jpg',
    duration: '138 min',
    cast: ['Leonardo DiCaprio'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-030',
    title: 'Coco',
    year: '2017',
    genre: 'Animación / Familiar',
    director: 'Lee Unkrich',
    synopsis: 'Un niño viaja al mundo de los muertos para descubrir su legado familiar.',
    posterUrl: 'https://m.media-amazon.com/images/I/71X9qLf+uIL._AC_UF894,1000_QL80_.jpg',
    duration: '105 min',
    cast: ['Anthony Gonzalez'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-031',
    title: 'El Lobo de Wall Street',
    year: '2013',
    genre: 'Drama / Biografía',
    director: 'Martin Scorsese',
    synopsis: 'La historia del ascenso y caída del corredor de bolsa Jordan Belfort.',
    posterUrl: 'https://m.media-amazon.com/images/I/91m2MB2lYFL._AC_UF894,1000_QL80_.jpg',
    duration: '180 min',
    cast: ['Leonardo DiCaprio', 'Jonah Hill'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-032',
    title: 'Alien: El Octavo Pasajero',
    year: '1979',
    genre: 'Ciencia Ficción / Terror',
    director: 'Ridley Scott',
    synopsis: 'La tripulación de una nave espacial es acechada por una criatura alienígena.',
    posterUrl: 'https://m.media-amazon.com/images/I/71S7+AVaVXL._AC_UF1000,1000_QL80_.jpg',
    duration: '117 min',
    cast: ['Sigourney Weaver'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-033',
    title: 'Terminator 2: El Juicio Final',
    year: '1991',
    genre: 'Acción / Ciencia Ficción',
    director: 'James Cameron',
    synopsis: 'Un cyborg protege a un joven que será clave para el futuro de la humanidad.',
    posterUrl: 'https://m.media-amazon.com/images/I/71wZBWEI23L._AC_UF894,1000_QL80_.jpg',
    duration: '137 min',
    cast: ['Arnold Schwarzenegger', 'Linda Hamilton'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-034',
    title: 'Jurassic Park',
    year: '1993',
    genre: 'Aventura / Ciencia Ficción',
    director: 'Steven Spielberg',
    synopsis: 'Un parque temático con dinosaurios clonados se convierte en una pesadilla.',
    posterUrl: 'https://m.media-amazon.com/images/I/91FeBLC-PGL._AC_UF894,1000_QL80_.jpg',
    duration: '127 min',
    cast: ['Sam Neill', 'Laura Dern'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-035',
    title: 'El Show de Truman',
    year: '1998',
    genre: 'Drama / Ciencia Ficción',
    director: 'Peter Weir',
    synopsis: 'Un hombre descubre que su vida es en realidad un programa de televisión.',
    posterUrl: 'https://m.media-amazon.com/images/I/819457MtAeL.jpg',
    duration: '103 min',
    cast: ['Jim Carrey'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-036',
    title: 'El Resplandor',
    year: '1980',
    genre: 'Terror / Drama',
    director: 'Stanley Kubrick',
    synopsis: 'Un escritor pierde la cordura mientras cuida un hotel aislado en invierno.',
    posterUrl: 'https://m.media-amazon.com/images/I/71ni6-n3z5L.jpg',
    duration: '146 min',
    cast: ['Jack Nicholson'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-037',
    title: 'Rocky',
    year: '1976',
    genre: 'Drama / Deporte',
    director: 'John G. Avildsen',
    synopsis: 'Un boxeador desconocido recibe la oportunidad de su vida.',
    posterUrl: 'https://m.media-amazon.com/images/I/51BQVK34JWL._AC_UF1000,1000_QL80_.jpg',
    duration: '120 min',
    cast: ['Sylvester Stallone'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-038',
    title: 'El Sexto Sentido',
    year: '1999',
    genre: 'Thriller / Misterio',
    director: 'M. Night Shyamalan',
    synopsis: 'Un niño afirma ver personas muertas y un psicólogo intenta ayudarlo.',
    posterUrl: 'https://m.media-amazon.com/images/I/71QqwqId1HL._AC_UF894,1000_QL80_.jpg',
    duration: '107 min',
    cast: ['Bruce Willis', 'Haley Joel Osment'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-039',
    title: 'Toy Story',
    year: '1995',
    genre: 'Animación / Familiar',
    director: 'John Lasseter',
    synopsis: 'Los juguetes cobran vida cuando los humanos no están presentes.',
    posterUrl: 'https://m.media-amazon.com/images/I/81qsBQZI3uL._AC_UF1000,1000_QL80_.jpg',
    duration: '81 min',
    cast: ['Tom Hanks', 'Tim Allen'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-040',
    title: 'Up',
    year: '2009',
    genre: 'Animación / Aventura',
    director: 'Pete Docter',
    synopsis: 'Un anciano viaja a Sudamérica en una casa sostenida por globos.',
    posterUrl: 'https://m.media-amazon.com/images/I/81JOqsD2NmL._AC_UF894,1000_QL80_.jpg',
    duration: '96 min',
    cast: ['Ed Asner'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-041',
    title: 'El Laberinto del Fauno',
    year: '2006',
    genre: 'Fantasía / Drama',
    director: 'Guillermo del Toro',
    synopsis: 'Una niña descubre un mundo mágico en la España franquista.',
    posterUrl: 'https://m.media-amazon.com/images/I/71A+RXry+2L.jpg',
    duration: '118 min',
    cast: ['Ivana Baquero'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-042',
    title: 'Amélie',
    year: '2001',
    genre: 'Romance / Comedia',
    director: 'Jean-Pierre Jeunet',
    synopsis: 'Una joven decide cambiar la vida de quienes la rodean para mejor.',
    posterUrl: 'https://m.media-amazon.com/images/I/416BFRC1EPL._AC_UF894,1000_QL80_.jpg',
    duration: '122 min',
    cast: ['Audrey Tautou'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-043',
    title: 'Drive',
    year: '2011',
    genre: 'Thriller / Crimen',
    director: 'Nicolas Winding Refn',
    synopsis: 'Un conductor especialista en huidas se ve envuelto en una conspiración.',
    posterUrl: 'https://m.media-amazon.com/images/I/615ot6U8mgL._AC_UF894,1000_QL80_.jpg',
    duration: '100 min',
    cast: ['Ryan Gosling'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-044',
    title: 'Memento',
    year: '2000',
    genre: 'Thriller / Misterio',
    director: 'Christopher Nolan',
    synopsis: 'Un hombre con pérdida de memoria intenta encontrar al asesino de su esposa.',
    posterUrl: 'https://m.media-amazon.com/images/I/A13FN6JYP0L._AC_UF894,1000_QL80_.jpg',
    duration: '113 min',
    cast: ['Guy Pearce'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-045',
    title: 'Her',
    year: '2013',
    genre: 'Drama / Ciencia Ficción',
    director: 'Spike Jonze',
    synopsis: 'Un hombre se enamora de un sistema operativo con inteligencia artificial.',
    posterUrl: 'https://m.media-amazon.com/images/I/71JMZFIQPmL._AC_UF894,1000_QL80_.jpg',
    duration: '126 min',
    cast: ['Joaquin Phoenix'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-046',
    title: 'The Prestige',
    year: '2006',
    genre: 'Drama / Misterio',
    director: 'Christopher Nolan',
    synopsis: 'Dos magos rivales compiten obsesivamente por crear el mejor truco.',
    posterUrl: 'https://m.media-amazon.com/images/I/51fdJ4G-gLL.jpg',
    duration: '130 min',
    cast: ['Hugh Jackman', 'Christian Bale'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-047',
    title: 'Bohemian Rhapsody',
    year: '2018',
    genre: 'Biografía / Música',
    director: 'Bryan Singer',
    synopsis: 'La historia de Freddie Mercury y la banda Queen.',
    posterUrl: 'https://m.media-amazon.com/images/I/91sLchfSmpL._UF894,1000_QL80_.jpg',
    duration: '134 min',
    cast: ['Rami Malek'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-048',
    title: 'La Llegada',
    year: '2016',
    genre: 'Ciencia Ficción / Drama',
    director: 'Denis Villeneuve',
    synopsis: 'Una lingüista intenta comunicarse con alienígenas que llegan a la Tierra.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNjFhNWU4MGMtNTZiNi00YTUwLWE1OGYtYmI4ODNlMGU3MWNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    duration: '116 min',
    cast: ['Amy Adams'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-049',
    title: 'Batman Begins',
    year: '2005',
    genre: 'Acción / Drama',
    director: 'Christopher Nolan',
    synopsis: 'El origen de Bruce Wayne como el vigilante de Gotham.',
    posterUrl: 'https://m.media-amazon.com/images/I/61YTXv90KnL._AC_UF894,1000_QL80_.jpg',
    duration: '140 min',
    cast: ['Christian Bale'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-050',
    title: 'Piratas del Caribe: La Maldición del Perla Negra',
    year: '2003',
    genre: 'Aventura / Fantasía',
    director: 'Gore Verbinski',
    synopsis: 'Un pirata excéntrico intenta recuperar su barco maldito.',
    posterUrl: 'https://m.media-amazon.com/images/I/513lBcl+ZdL._AC_UF350,350_QL50_.jpg',
    duration: '143 min',
    cast: ['Johnny Depp', 'Orlando Bloom'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-051',
    title: 'Kill Bill: Vol. 1',
    year: '2003',
    genre: 'Acción / Crimen',
    director: 'Quentin Tarantino',
    synopsis: 'Una asesina despierta del coma y busca venganza contra su antiguo equipo.',
    posterUrl: 'https://m.media-amazon.com/images/I/71pXZoNF4yL._AC_UF894,1000_QL80_.jpg',
    duration: '111 min',
    cast: ['Uma Thurman'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-052',
    title: 'El Exorcista',
    year: '1973',
    genre: 'Terror',
    director: 'William Friedkin',
    synopsis: 'Una niña es poseída por una entidad demoníaca.',
    posterUrl: 'https://m.media-amazon.com/images/I/71tcBAml75L._UF1000,1000_QL80_.jpg',
    duration: '122 min',
    cast: ['Ellen Burstyn'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-053',
    title: 'Indiana Jones y los Cazadores del Arca Perdida',
    year: '1981',
    genre: 'Aventura / Acción',
    director: 'Steven Spielberg',
    synopsis: 'Un arqueólogo aventurero busca el Arca de la Alianza.',
    posterUrl: 'https://m.media-amazon.com/images/I/51NN7BM8EAL._AC_UF894,1000_QL80_.jpg',
    duration: '115 min',
    cast: ['Harrison Ford'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-054',
    title: 'El Rey León',
    year: '1994',
    genre: 'Animación / Drama',
    director: 'Roger Allers',
    synopsis: 'Un joven león debe reclamar su lugar como rey.',
    posterUrl: 'https://m.media-amazon.com/images/I/715EaibY6gL._AC_UF894,1000_QL80_.jpg',
    duration: '88 min',
    cast: ['Matthew Broderick'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-055',
    title: 'El Gran Dictador',
    year: '1940',
    genre: 'Comedia / Drama',
    director: 'Charles Chaplin',
    synopsis: 'Sátira política sobre el auge del fascismo en Europa.',
    posterUrl: 'https://m.media-amazon.com/images/I/7156dCsOoYL._AC_UF894,1000_QL80_.jpg',
    duration: '125 min',
    cast: ['Charles Chaplin'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-056',
    title: '12 Años de Esclavitud',
    year: '2013',
    genre: 'Drama / Histórico',
    director: 'Steve McQueen',
    synopsis: 'La historia real de un hombre libre vendido como esclavo.',
    posterUrl: 'https://m.media-amazon.com/images/I/51OTlAls+-L._AC_UF894,1000_QL80_.jpg',
    duration: '134 min',
    cast: ['Chiwetel Ejiofor'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-057',
    title: 'El Código Da Vinci',
    year: '2006',
    genre: 'Thriller / Misterio',
    director: 'Ron Howard',
    synopsis: 'Un profesor investiga un misterio oculto en obras de arte religiosas.',
    posterUrl: 'https://m.media-amazon.com/images/I/71PR0C4XNjL._AC_UF1000,1000_QL80_.jpg',
    duration: '149 min',
    cast: ['Tom Hanks'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-058',
    title: 'Gran Torino',
    year: '2008',
    genre: 'Drama',
    director: 'Clint Eastwood',
    synopsis: 'Un veterano gruñón entabla amistad con su joven vecino.',
    posterUrl: 'https://m.media-amazon.com/images/I/4101b54DxdL._AC_UF894,1000_QL80_.jpg',
    duration: '116 min',
    cast: ['Clint Eastwood'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-059',
    title: 'Logan',
    year: '2017',
    genre: 'Acción / Drama',
    director: 'James Mangold',
    synopsis: 'Un envejecido Wolverine protege a una joven mutante.',
    posterUrl: 'https://m.media-amazon.com/images/I/41hfzl3nj2L._AC_UF894,1000_QL80_.jpg',
    duration: '137 min',
    cast: ['Hugh Jackman'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-060',
    title: 'El Origen del Planeta de los Simios',
    year: '2011',
    genre: 'Ciencia Ficción / Acción',
    director: 'Rupert Wyatt',
    synopsis: 'Un experimento científico da origen a una revolución simiesca.',
    posterUrl: 'https://m.media-amazon.com/images/I/81ONfNCY9UL.jpg',
    duration: '105 min',
    cast: ['James Franco'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-061',
    title: '1917',
    year: '2019',
    genre: 'Drama / Bélico',
    director: 'Sam Mendes',
    synopsis: 'Dos soldados británicos deben cruzar territorio enemigo para entregar un mensaje crucial.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BYzY0NjE0YTktN2Q3Zi00ZTY0LWE5NzUtYzFjN2E0ZTM0NTc5XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg',
    duration: '119 min',
    cast: ['George MacKay', 'Dean-Charles Chapman'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-062',
    title: 'Ford v Ferrari',
    year: '2019',
    genre: 'Drama / Deporte',
    director: 'James Mangold',
    synopsis: 'La historia real del equipo que desafió a Ferrari en Le Mans 1966.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BM2YxY2M2ZTAtYzU0ZC00YmJhLTk1YzAtYjQzN2E1YjZiYjM4XkEyXkFqcGdeQXVyNjUxMjc1OTM@._V1_SX300.jpg',
    duration: '152 min',
    cast: ['Matt Damon', 'Christian Bale'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-063',
    title: 'Green Book',
    year: '2018',
    genre: 'Drama / Biografía',
    director: 'Peter Farrelly',
    synopsis: 'Un pianista afroamericano y su chófer recorren el sur segregado de EE.UU.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNzY2MjA5NzAtZDU2My00YzZhLWI4Y2ItZjRkY2Y0NTZlZDY1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
    duration: '130 min',
    cast: ['Viggo Mortensen', 'Mahershala Ali'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-064',
    title: 'The Social Network',
    year: '2010',
    genre: 'Drama / Biografía',
    director: 'David Fincher',
    synopsis: 'La creación de Facebook y los conflictos legales que surgieron.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTk1MzY3NjY3OF5BMl5BanBnXkFtZTcwNDk2NzMzMw@@._V1_SX300.jpg',
    duration: '120 min',
    cast: ['Jesse Eisenberg', 'Andrew Garfield'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-065',
    title: 'El Gran Lebowski',
    year: '1998',
    genre: 'Comedia / Crimen',
    director: 'Joel Coen',
    synopsis: 'Un hombre confundido con un millonario se ve envuelto en un secuestro.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNzA5ZDM2YzQtZDVhNi00YzUwLTg0ZDEtZjE3YjU0YjQ5Y2E0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    duration: '117 min',
    cast: ['Jeff Bridges', 'John Goodman'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-066',
    title: 'La Terminal',
    year: '2004',
    genre: 'Comedia / Drama',
    director: 'Steven Spielberg',
    synopsis: 'Un hombre queda atrapado en un aeropuerto por problemas diplomáticos.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTQ1NjM5OTg3Nl5BMl5BanBnXkFtZTcwNjE0ODIyMw@@._V1_SX300.jpg',
    duration: '128 min',
    cast: ['Tom Hanks'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-067',
    title: 'El Irlandés',
    year: '2019',
    genre: 'Crimen / Drama',
    director: 'Martin Scorsese',
    synopsis: 'Un sicario recuerda su implicación en la desaparición de Jimmy Hoffa.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMmU5NDE4Y2UtZmYzZC00YjY3LWE4ZjItNDRhODNlMzBjMTk3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
    duration: '209 min',
    cast: ['Robert De Niro', 'Al Pacino'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-068',
    title: 'El Hombre Araña: Un Nuevo Universo',
    year: '2018',
    genre: 'Animación / Acción',
    director: 'Bob Persichetti',
    synopsis: 'Miles Morales se convierte en Spider-Man en un universo alternativo.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNjU2NzU2MDktNzU3OC00MjM4LTg4MzUtYzYzYjI3NzYxZGRmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
    duration: '117 min',
    cast: ['Shameik Moore'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-069',
    title: 'Black Swan',
    year: '2010',
    genre: 'Drama / Thriller',
    director: 'Darren Aronofsky',
    synopsis: 'Una bailarina obsesionada pierde el control mientras prepara El Lago de los Cisnes.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjE3MzY0Mjc0NV5BMl5BanBnXkFtZTcwNzU4NjYyNA@@._V1_SX300.jpg',
    duration: '108 min',
    cast: ['Natalie Portman'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-070',
    title: 'La Teoría del Todo',
    year: '2014',
    genre: 'Biografía / Drama',
    director: 'James Marsh',
    synopsis: 'La vida del físico Stephen Hawking y su relación con Jane Wilde.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjA4NzI2OTQxNV5BMl5BanBnXkFtZTgwNzE4OTM1MzE@._V1_SX300.jpg',
    duration: '123 min',
    cast: ['Eddie Redmayne'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-071',
    title: 'El Juego de la Imitación',
    year: '2014',
    genre: 'Biografía / Drama',
    director: 'Morten Tyldum',
    synopsis: 'Alan Turing lidera el descifrado de Enigma durante la Segunda Guerra Mundial.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BOTAzNTg3NzYxMl5BMl5BanBnXkFtZTgwNzY2OTM1MzE@._V1_SX300.jpg',
    duration: '114 min',
    cast: ['Benedict Cumberbatch'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-072',
    title: 'El Hobbit: Un Viaje Inesperado',
    year: '2012',
    genre: 'Fantasía / Aventura',
    director: 'Peter Jackson',
    synopsis: 'Bilbo Bolsón se une a un grupo de enanos para recuperar su reino.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTk3OTMyMDQ4NV5BMl5BanBnXkFtZTcwNjc5MTY5OA@@._V1_SX300.jpg',
    duration: '169 min',
    cast: ['Martin Freeman'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-073',
    title: 'Dune',
    year: '2021',
    genre: 'Ciencia Ficción / Aventura',
    director: 'Denis Villeneuve',
    synopsis: 'Paul Atreides viaja al peligroso planeta Arrakis.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNWIyNzU3ZTUtYzU4Zi00YmE4LTkzZTktZTYxYjMxYzE2Y2M4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
    duration: '155 min',
    cast: ['Timothée Chalamet'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-074',
    title: 'Oppenheimer',
    year: '2023',
    genre: 'Drama / Biografía',
    director: 'Christopher Nolan',
    synopsis: 'La historia del físico J. Robert Oppenheimer y el Proyecto Manhattan.',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BM2I1YzQxZTItNzRhZi00MzAwLTgxNjUtYzM4YjE4Y2JmYjVkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
    duration: '180 min',
    cast: ['Cillian Murphy'],
    averageRating: 0,
    totalRatings: 0,
  },
  {
    id: 'movie-075',
    title: 'Barbie',
    year: '2023',
    genre: 'Comedia / Fantasía',
    director: 'Greta Gerwig',
    synopsis: 'Barbie abandona Barbieland para descubrir el mundo real.',
    posterUrl: 'https://m.media-amazon.com/images/I/81f3zkhz2rL._AC_UF894,1000_QL80_.jpg',
    duration: '114 min',
    cast: ['Margot Robbie', 'Ryan Gosling'],
    averageRating: 0,
    totalRatings: 0,
  },
];

export const seedMovies = async () => {
  try {
    for (const movie of SAMPLE_MOVIES) {
      const { id, ...data } = movie;
      await setDoc(doc(collection(db, 'movies'), id), data);
    }
    console.log('✅ Movies seeded successfully!');
  } catch (error) {
    console.error('❌ Error seeding movies:', error);
  }
};
